on:
  workflow_dispatch:
  schedule:
    # every hour
    - cron: '30 * * * *'

name: 'Check for OpenMRS Dependency Updates'

jobs:
  check-for-updates:
    name: Check for updates to OpenMRS libraries
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'openmrs'

    steps:
      - uses: actions/checkout@v4
      - name: ðŸŸ¢ Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: ðŸ’¾ Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: ðŸ“¦ Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: âœ… Check for updates
        run: node ./tools/update-openmrs-deps.mjs
      - name: â¬†ï¸ Create PR if necessary
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: '(chore) Update OpenMRS dependencies'
          title: '(chore) Update OpenMRS dependencies'
          body: |
            # OpenMRS Dependencies Update

            This PR contains updates to OpenMRS dependencies.

            ## Changes
            * Automated dependency updates for OpenMRS packages
            * Generated by the OpenMRS Dependency Update workflow

            ## Verification
            - [ ] All dependencies are valid versions
            - [ ] No breaking changes introduced

            > This PR was automatically generated and will be automatically merged if checks pass.
          branch: 'chore/update-openmrs-deps'
          author: 'OpenMRS Bot <infrastructure@openmrs.org>'
          token: ${{ secrets.OMRS_BOT_GH_TOKEN }}
      - name: âœ… Auto approve PR
        if: steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated'
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ðŸ”€ Automerge PR
        if: steps.cpr.outputs.pull-request-operation == 'created' || steps.cpr.outputs.pull-request-operation == 'updated'
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.OMRS_BOT_GH_TOKEN }}
